In [1]:
import pandas as pd
from sklearn.datasets import load_files
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score,accuracy_score

In [2]:
#Reading the csv file of term document frequency generated in R
input_data = pd.read_csv("finamatrix.csv",index_col=0, header =0 )

In [30]:
type(input_data)

pandas.core.frame.DataFrame

In [31]:
real_input = input_data.values

In [44]:
real_input

array([[3, 1, 1, ..., 0, 0, 0],
       [9, 4, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
type(real_input)

numpy.ndarray

In [3]:
full_input = load_files('20news-18828',decode_error='ignore')

In [4]:
y = full_input['target']

In [45]:
y

array([ 1,  1,  0, ..., 10, 11,  2])

In [5]:
#Normalizing the data within a scale range
x = preprocessing.MinMaxScaler()
X = x.fit_transform(input_data)

In [29]:
y.shape

(18828,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

In [9]:
knn = KNeighborsClassifier(n_jobs=1)

In [10]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [11]:
predicted = knn.predict(X_test)

In [12]:
predicted.shape

(3766,)

In [13]:
accuracy_score(y_test,predicted)

0.048327137546468404

In [34]:
scores = cross_val_score(knn, real_input, y, cv=5,scoring='accuracy')

In [43]:
scores

array([0.04931071, 0.05200318, 0.04727756, 0.05341483, 0.04708699])

In [42]:
scores.mean()

0.04981865412459773

In [16]:
f1_scores = cross_val_score(knn, X, y, cv=5,scoring='f1_weighted')

In [17]:
f1_scores.mean()

0.04164598470682126

In [27]:
f1_score(y_test,predicted,average=None)

array([0.05846154, 0.06417112, 0.07577808, 0.064     , 0.04824561,
       0.05825243, 0.065     , 0.03878116, 0.06097561, 0.03030303,
       0.01438849, 0.03436426, 0.03460208, 0.02597403, 0.04844291,
       0.00766284, 0.01612903, 0.03162055, 0.05932203, 0.        ])